language: swift

branches:
  only:
    - master

podfile: ./Demo/Podfile
osx_image: xcode11
cache: cocoapods

script:
  - xcodebuild -workspace ./Demo/Demo.xcworkspace -scheme Demo -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
